services:
  - type: web
    name: castline-backend
    runtime: node
    plan: free
    buildCommand: corepack yarn install --immutable && corepack yarn workspace backend build
    startCommand: corepack yarn workspace backend start
    envVars:
      - key: FRONTEND_ORIGIN
        sync: false
      - key: NODE_ENV
        value: production
